# Site
repository: hx077/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lourdes Cigarruista
title: Cybersecurity Engineer
email: lourdes.cigarruista@gmail.com
Phone#: 856-994-8299

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  hx077
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: lourdes-cigarruista
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Personal Blog
  icon: fas fa-globe
  url: https://hx77.rocks
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/mugshot1.jpg
about_content: | # this will include new lines to allow paragraphs
  Cybersecurity professional with 15 years of experience and a Secret security clearance with expertise in penetration testing, incident response, vulnerability assessments, security audits, and automation (Python). Highly skilled in risk identification, mitigation strategies, and enhancing operational efficiency through innovative solutions. Fluent in English and Spanish with strong communication, leadership, and teamwork skills.
  
  I am most skilled in:  

  <mark>Core:</mark> Incident Response, Penetration Testing, Vulnerability Scanning, Vulnerability Remediation, Cross-Team Collaboration, Cybersecurity Risk Management, Risk Mitigation, Project Management Process Documentation, System Administration.

  <mark>Technical:</mark> Java, Python, Security Tools, Risk Management, MS Exchange & Active Directory, PowerShell, Service Now, MS Azure, Cisco (VPN, WebEx, VoIP), Office 365.

    <mark>Platforms:</mark> Microsoft Windows, Windows Server 2016 & 2019, Kali, Ubuntu, Parrot, Red Hat Enterprise Linux.






 # I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
#   - title: Work Experience # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: top-middle
#         title: Cybersecurity Engineer
#         quote: >
#           Lincoln Investment Planning, Fort Washington, PA | 2023, Present
        #link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.



  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Lincoln Investment Planning
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Cybersecurity Engineer
        caption: November 2023 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        #description: | # this will include new lines to allow paragraphs
            #Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
        description: | # this will include new lines to allow paragraphs

              - Lead a quarterly penetration testing program covering 500+ internal, cloud and external targets, identifying vulnerabilities and coordinating remediation efforts across teams.
              - Administrator for Knowbe4, Zscaler (ZIA, ZPA, Deception) and CrowdStrike, co-administrator for Palo Alto firewalls and Cisco Meraki.
              - Lead key security implementations including Zscaler, Extrahop and other cloud-based tools.
              - Spearheaded phishing awareness training and employee education initiatives to enhance organizational security posture.
              - Built and currently manage company-wide programs for vulnerability detection, phishing detection and penetration testing.
              - Implemented and enforced network security measures and policies, ensuring compliance with industry standards (NIST and FINRA) and driving continuous improvement in security practices.
              - Contributed to the development and implementation of a SIEM system for efficient alert management and enhanced threat detection.
              - Act as the final escalation point for complex technical and security issues, ensuring resolution when all other options have been exhausted.

  - title: #Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: United States Air Force Reserve
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Staff Sargeant, Aircraft Hydraulics Systems
        caption: November 2016 - 2024
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        #description: | # this will include new lines to allow paragraphs
            #Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
        description: | # this will include new lines to allow paragraphs

              - Troubleshot, repaired, and maintained aircraft hydraulic systems, components, and support equipment, ensuring optimal performance and compliance with quality standards.
              - Assessed and validated work to ensure adherence to internal protocols and high-quality maintenance practices.


              - Awarded Airman of the Quarter, 4th Quarter 2021, for outstanding performance and leadership during critical projects.


  - title: #Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sonepar USA 
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Cybersecurity Analyst
        caption: November 2021 - 2023
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        #description: | # this will include new lines to allow paragraphs
            #Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
        description: | # this will include new lines to allow paragraphs

              •	Performed technical lead cybersecurity functions, specializing in incident response, threat hunting, and alert investigation, providing expert guidance to users and IT Team.
              •	Proactively identified and neutralized cybersecurity threats, including network vulnerabilities and malware, safeguarding system integrity and data protection.
              •	Developed incident response documentation best practices, detailing all phases from detection to recovery, and coordinated cross-functional teams to minimize damage and prevent recurrence.
              •	Engineered and deployed Python scripts to automate essential security tasks, improving efficiency and response times by 20%.
              •	Provided risk assessments, developed security plans, and implemented control measures to minimize exposure to cyber-attacks and ensure rapid recovery from incidents. 


  - title: #Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sonepar USA 
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Technical Support II
        caption: November 2010 - 2021
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        #description: | # this will include new lines to allow paragraphs
            #Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
        description: | # this will include new lines to allow paragraphs

                •	Performed system administration duties, ensuring proper deployment and maintenance across multiple platforms like MS Exchange, Active Directory, Office 365, MS Azure, and Citrix. 
                •	Played a key role in critical offsite and onsite migrations, including Exchange-to-cloud and MS Office 2007-to-2016 upgrades, impacting 8K+ end users and 10K+ computers.
                •	Created and launched training materials and knowledge base documents boosting team operational efficiency, reducing resolution times.
                •	Effectively launched, supported and troubleshooted a successful MS MFA project for 13K users nationwide.
                •	Provided technical support, resolving 400+ calls and 380+ tickets monthly while troubleshooting hardware and software issues.
                •	Managed the support queue, delegating tickets and tasks to the technical team to optimize efficiency.





  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Maryland Global Campus
        caption: Bachelor of Science in Computer Science
        sub_title: Minor - Cybersecurity
        sub_title2: Cum Laude
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Member: Alpha Sigma Lambda Tau, Upsilon Pi Epsilon, Sigma Alpha Pi


        content:
          - layout: left
            title: Rowan College at Burlington County
            caption: Associate of Science
            # quote: >
            #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
